export const optionsTime = [
  { value: '24/48h', label: '24/48h'},
  { value: '1/2 días laborables', label: '1/2 días laborables' },
  { value: '2/3 días laborables', label: '2/3 días laborables'},
  { value: '3/5 días laborables', label: '3/5 días laborables'},
  { value: 'Una semana', label: 'Una semana'},
  { value: '10 días laborables', label: '10 días laborables'},
  { value: 'Dos semanas', label: 'Dos semanas'},
]

export const optionProvinces = [
  { label: 'A Coruña', value: 'A Coruña' },
  { label: 'Álava', value: 'Álava'},
  { label: 'Albacete', value: 'Albacete' },
  { label: 'Alicante', value: 'Alicante' },
  { label: 'Almería', value: 'Almería'},
  { label: 'Asturias', value: 'Asturias'},
  { label: 'Ávila', value: 'Ávila'},
  { label: 'Badajoz', value: 'Badajoz'},
  { label: 'Baleares', value: 'Baleares'},
  { label: 'Barcelona', value: 'Barcelona'},
  { label: 'Burgos', value: 'Burgos'},
  { label: 'Cáceres', value: 'Cáceres'},
  { label: 'Cádiz', value: 'Cádiz'},
  { label: 'Cantabria', value: 'Cantabria'},
  { label: 'Castellón', value: 'Castellón'},
  { label: 'Ceuta', value: 'Ceuta'},
  { label: 'Ciudad Real', value: 'Ciudad Real'},
  { label: 'Córdoba', value: 'Córdoba'},
  { label: 'Cuenca', value: 'Cuenca'},
  { label: 'Gerona', value: 'Gerona'},
  { label: 'Granada', value: 'Granada'},
  { label: 'Guadalajara', value: 'Guadalajara'},
  { label: 'Gipúzcuoa', value: 'Gipúzcuoa'},
  { label: 'Huelva', value: 'Huelva'},
  { label: 'Huesca', value: 'Huesca'},
  { label: 'Jaén', value: 'Jaén '},
  { label: 'La Rioja', value: 'La Rioja'},
  { label: 'Las Palmas', value: 'Las Palmas' },
  { label: 'León', value: 'León' },
  { label: 'Lérida', value: 'Lérida'},
  { label: 'Lugo', value: 'Lugo'},
  { label: 'Madrid', value: 'Madrid' },
  { label: 'Málaga', value: 'Málaga' },
  { label: 'Melilla', value: 'Melilla' },
  { label: 'Murcia', value: 'Murcia'},
  { label: 'Navarra', value: 'Navarra'},
  { label: 'Orense', value: 'Orense' },
  { label: 'Palencia', value: 'Palencia' },
  { label: 'Pontevedra', value: 'Pontevedra' },
  { label: 'Salamanca', value: 'Salamanca' },
  { label: 'Segovia', value: 'Segovia'},
  { label: 'Sevilla', value: 'Sevilla'},
  { label: 'Soria', value: 'Soria' },
  { label: 'Tarragona', value: 'Tarragona'},
  { label: 'Santa Cruz de Tenerife', value: 'Santa Cruz de Tenerife'} ,
  { label: 'Teruel', value: 'Teruel'},
  { label: 'Toledo', value: 'Toledo' },
  { label: 'Valencia', value: 'Valencia' },
  { label: 'Valladolid', value: 'Valladolid'},
  { label: 'Vizcaya', value: 'Vizcaya'},
  { label: 'Zamora', value: 'Zamora'},
  { label: 'Zaragoza', value: 'Zaragoza'},
]
